공유기능고도화
Team-MTG/FrontEnd pull request #18
Opened 2023-01-09 05:11 UTC by hyeonzii

2023-01-09 12:58 UTC, chb09876 commented on src/Rankings.jsx
> +  let url = window.document.location.href + '?username=' + userName; //url에는 현재 주소값을 넣어줌;
혹시 요기 let으로 변수 선언하신 이유가 있을까용?

copyURL함수에서 url변수를 사용하기 때문인거 같은데 copyURL함수에서 url변수를 재사용할 필요가 있나 싶습니다.

해당 변수는 const로 바꾸고 copyURL함수에서 다른 url변수를 선언하는게 어떨까요?

2023-01-09 13:00 UTC, chb09876 requested changes
해당 사항 확인 부탁드립니다!

2023-01-09 13:34 UTC, hyeonzii commented on src/Rankings.jsx
> +  let url = window.document.location.href + '?username=' + userName; //url에는 현재 주소값을 넣어줌;
음 제가 실수한 것 같습니다! 수정해서 다시 올리겠습니다~~

2023-01-09 13:36 UTC, hyeonzii commented
수정한거 올리면서 tailwind로 변경한 것도 함께 올렸습니다!

2023-01-10 03:08 UTC, chb09876 requested changes

2023-01-10 03:08 UTC, chb09876 commented on src/Rankings.jsx
>    const copyURL = () => {
copy URL함수에서 url변수에 무언가를 대입하잖아요.
그때의 url변수는 위에서 선언한 const url에 대해 접근을 합니다. 그러면 당연히 const를 바꾸려 해서 오류가 나겠죠.
그래서 copy URL 함수에서 따로 const url을 선언하거나 textarea.value = window.document.location.href로 바로 대입하는게 나아보여요
```javascript
const url = window.document.location.href
```
또는 바로 대입...
```javascript
textarea.value = window.document.location.href
```

2023-01-10 04:05 UTC, chb09876 approved these changes

2023-01-10 04:05 UTC, merged